# Generated by Django 5.2.11 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(default='good morning', max_length=70),
            preserve_default=False,
        ),
    ]
