# Generated by Django 5.2.11 on 2026-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Raj', max_length=40),
        ),
    ]
